#!/bin/sh
nm="gipfs"
vs="r1"
itsversion="""
        \e[1;42m $nm \e[0m\e[100m version $vs \e[0m
        \e[100m Created by Daniella Mesquita \e[0m
"""
#should get from config file in common with gipfs

# Only run normal ipfs at commands unknown to gipfs's ipfs wrapper
if [[ "$2" != "make" ]];then
if [[ "$2" != "validate" ]];then
if [[ "$2" != "convert" ]];then
if [[ "$1" != "ass" ]];then
/usr/bin/./ipfsoriginal "$@"
fi
fi
fi
fi

# make a .cid file from another file!
if [[ "$1" = "cid" ]];then
if [[ "$2" = "make" ]];then
if [[ "$3" != "" ]]
then
   ipfsoriginal add -q --only-hash "$3" >> "$3".cid
else
   echo "Please tell what file you want to get a CID from. Only one file per once."
fi
fi
fi

# validate a cid format
if [[ "$1" = "cid" ]];then
if [[ "$2" = "validate" ]];then
if [[ "$3" != "" ]]
then
   if echo $3 | elcid d >/dev/null 2>&1; then echo "✅ Valid CID"; exit 0; else echo "❌ Invalid CID"; exit 1; fi
# from https://discuss.ipfs.tech/t/is-there-a-way-to-determine-if-a-string-is-a-valid-ipfs-multihash/1248/7?u=daniellmesquita
else
   echo "Please tell what hash (CID) you want to validate. Only one per once."
fi
fi
fi

# convert CID v1 to v2
if [[ "$1" = "cid" ]];then
if [[ "$2" = "convert" ]];then
if [[ "$3" != "" ]]
then
   echo "$3" | ipfsoriginal cid base32
else
   echo "Please tell what CID v1 you want to convert to v2. Only one per once."
fi
fi
fi

# get the CID of a folder
if [[ "$1" = "cid" ]];then
if [[ "$2" = "folder" ]];then
if [[ "$3" != "" ]]
then
   ipfsoriginal add -Qr --only-hash "$3"
   #from https://discuss.ipfs.tech/t/how-to-get-the-cid-of-a-folder/12614/2?u=daniellmesquita
else
   echo "Please tell the folder name you want to get the CID from. Only one folder per once."
fi
fi
fi

# traps for misspells
if [[ "$1" = "ass" ]];then echo "Did you mean \"ipfs add\"? If that's not what you mean, it may be the time to take a break...";fi

# displays help message with a list of commands:
if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
   echo "       ipfs wrapper - \e[1;42m $nm $vs \e[0m"
#   echo "Information:"
#   echo "   --help, -h                  Shows all available commands"
   echo "Work w/ CIDs:"
   echo "   cid make <file/extension>   Get a .cid file of a file/extension. Only one file per once."
   echo "   cid validate <hash>         Check if a hash is a valid IPFS CID."
   echo "   cid convert <hash>          Convert CID v1 to v2."
   echo "   cid folder <folder-name>    Get the CID of a folder."
   echo "------------------------------"
fi
